name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@08d09a53f0f5d694f253bd25732e4429c9e9337f # v3
        with:
          languages: go, javascript
          build-mode: none

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@08d09a53f0f5d694f253bd25732e4429c9e9337f # v3
